### PR TITLE
Updates dependencies to work with node 8, react 16, etc

### PR DESCRIPTION
**Pull request by logankoester**

### CODE REVIEW

**Comment by AljoschaMeyer** [comment]
@logankoester: This project is about as unmaintained as it gets, would you mind if I simply transferred ownership to you?

**Comment by logankoester** [comment]
Sure, that's fine by me :+1:

**Comment by AljoschaMeyer** [comment]
Ok, github doesn't let me give you the repo as long as you have one of the same name (your fork). You can delete the fork, and then I'll move the repo.

**Comment by logankoester** [comment]
Okay @AljoschaMeyer I have deleted my fork. Please set npm owner as well. Cheers!

**Pull request merged**
